Paclet[
	Name -> "CloudObject",
	Version -> "0.0.2",
	MathematicaVersion -> "10.0+",
	Loading -> Automatic,
    Creator -> "Jan Poeschko <jpoeschko@wolfram.com>, Joel Klein <jfklein@wolfram.com>",
	Extensions -> {
		{"Kernel",
			Root->"Kernel",
			Context->{
                "CloudObjectLoader`",
                "CloudObject`"
            },
			Symbols-> {
				"System`$CloudBase",
				"System`$CloudConnected",
				"System`$CloudCreditsAvailable",
				"System`$CloudRootDirectory",
				"System`$CloudSymbolBase",
                "System`$Permissions",
                "System`$PermissionsGroupBase",
				"System`$RegisteredUserName",
                "System`AddUsers",
				"System`APIFunctionGroup",
				"System`CloudBase",
				"System`CloudAccountData",
				"System`CloudConnect",
				"System`CloudDeploy",
				"System`CloudDirectory",
				"System`CloudDisconnect",
				"System`CloudEvaluate",
				"System`CloudExport",
				"System`CloudFunction",
				"System`CloudGet",
				"System`CloudImport",
				"System`CloudObject",
				"System`CloudObjects",
				"System`CloudObjectInformation",
				"System`CloudObjectInformationData",
				"System`CloudPut",
				"System`CloudSave",
				"System`CloudSymbol",
                "System`CreatePermissionsGroup",
				"System`CreateUUID",
				"System`Delayed",
				"System`EvaluationData",
				"System`ExternalBundle",
				"System`ExportForm",
				"System`IconRules",
				"System`LocalizeDefinitions",
				"System`Permissions",
                "System`PermissionsGroup",
                "System`PermissionsGroups",
                "System`RemoveUsers",
				"System`ResponseForm",
				"System`ScheduledTask",
                "System`SetCloudDirectory",
                "System`SetUsers"
			}
		},
		{"Documentation", Language -> "English"},
		{"LibraryLink", Root->"LibraryResources"}
	}
]
